// Generated by gencpp from file capabilities/FreeCapabilityResponse.msg
// DO NOT EDIT!


#ifndef CAPABILITIES_MESSAGE_FREECAPABILITYRESPONSE_H
#define CAPABILITIES_MESSAGE_FREECAPABILITYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace capabilities
{
template <class ContainerAllocator>
struct FreeCapabilityResponse_
{
  typedef FreeCapabilityResponse_<ContainerAllocator> Type;

  FreeCapabilityResponse_()
    {
    }
  FreeCapabilityResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }






  typedef boost::shared_ptr< ::capabilities::FreeCapabilityResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::capabilities::FreeCapabilityResponse_<ContainerAllocator> const> ConstPtr;

}; // struct FreeCapabilityResponse_

typedef ::capabilities::FreeCapabilityResponse_<std::allocator<void> > FreeCapabilityResponse;

typedef boost::shared_ptr< ::capabilities::FreeCapabilityResponse > FreeCapabilityResponsePtr;
typedef boost::shared_ptr< ::capabilities::FreeCapabilityResponse const> FreeCapabilityResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::capabilities::FreeCapabilityResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::capabilities::FreeCapabilityResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace capabilities

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'capabilities': ['/tmp/binarydeb/ros-indigo-capabilities-0.2.0/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::capabilities::FreeCapabilityResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::capabilities::FreeCapabilityResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::capabilities::FreeCapabilityResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::capabilities::FreeCapabilityResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::capabilities::FreeCapabilityResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::capabilities::FreeCapabilityResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::capabilities::FreeCapabilityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::capabilities::FreeCapabilityResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::capabilities::FreeCapabilityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "capabilities/FreeCapabilityResponse";
  }

  static const char* value(const ::capabilities::FreeCapabilityResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::capabilities::FreeCapabilityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::capabilities::FreeCapabilityResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::capabilities::FreeCapabilityResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FreeCapabilityResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::capabilities::FreeCapabilityResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::capabilities::FreeCapabilityResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // CAPABILITIES_MESSAGE_FREECAPABILITYRESPONSE_H
