// Generated by gencpp from file capabilities/GetProvidersRequest.msg
// DO NOT EDIT!


#ifndef CAPABILITIES_MESSAGE_GETPROVIDERSREQUEST_H
#define CAPABILITIES_MESSAGE_GETPROVIDERSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace capabilities
{
template <class ContainerAllocator>
struct GetProvidersRequest_
{
  typedef GetProvidersRequest_<ContainerAllocator> Type;

  GetProvidersRequest_()
    : interface()
    , include_semantic(false)  {
    }
  GetProvidersRequest_(const ContainerAllocator& _alloc)
    : interface(_alloc)
    , include_semantic(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _interface_type;
  _interface_type interface;

   typedef uint8_t _include_semantic_type;
  _include_semantic_type include_semantic;




  typedef boost::shared_ptr< ::capabilities::GetProvidersRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::capabilities::GetProvidersRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetProvidersRequest_

typedef ::capabilities::GetProvidersRequest_<std::allocator<void> > GetProvidersRequest;

typedef boost::shared_ptr< ::capabilities::GetProvidersRequest > GetProvidersRequestPtr;
typedef boost::shared_ptr< ::capabilities::GetProvidersRequest const> GetProvidersRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::capabilities::GetProvidersRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::capabilities::GetProvidersRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace capabilities

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'capabilities': ['/tmp/binarydeb/ros-indigo-capabilities-0.2.0/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::capabilities::GetProvidersRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::capabilities::GetProvidersRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::capabilities::GetProvidersRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::capabilities::GetProvidersRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::capabilities::GetProvidersRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::capabilities::GetProvidersRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::capabilities::GetProvidersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ae99773830cfbf75aa47ccf9b6e5018e";
  }

  static const char* value(const ::capabilities::GetProvidersRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xae99773830cfbf75ULL;
  static const uint64_t static_value2 = 0xaa47ccf9b6e5018eULL;
};

template<class ContainerAllocator>
struct DataType< ::capabilities::GetProvidersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "capabilities/GetProvidersRequest";
  }

  static const char* value(const ::capabilities::GetProvidersRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::capabilities::GetProvidersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string interface\n\
bool include_semantic\n\
";
  }

  static const char* value(const ::capabilities::GetProvidersRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::capabilities::GetProvidersRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.interface);
      stream.next(m.include_semantic);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetProvidersRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::capabilities::GetProvidersRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::capabilities::GetProvidersRequest_<ContainerAllocator>& v)
  {
    s << indent << "interface: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.interface);
    s << indent << "include_semantic: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.include_semantic);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAPABILITIES_MESSAGE_GETPROVIDERSREQUEST_H
