// Generated by gencpp from file capabilities/StopCapabilityResponse.msg
// DO NOT EDIT!


#ifndef CAPABILITIES_MESSAGE_STOPCAPABILITYRESPONSE_H
#define CAPABILITIES_MESSAGE_STOPCAPABILITYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace capabilities
{
template <class ContainerAllocator>
struct StopCapabilityResponse_
{
  typedef StopCapabilityResponse_<ContainerAllocator> Type;

  StopCapabilityResponse_()
    : successful(false)  {
    }
  StopCapabilityResponse_(const ContainerAllocator& _alloc)
    : successful(false)  {
  (void)_alloc;
    }



   typedef uint8_t _successful_type;
  _successful_type successful;




  typedef boost::shared_ptr< ::capabilities::StopCapabilityResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::capabilities::StopCapabilityResponse_<ContainerAllocator> const> ConstPtr;

}; // struct StopCapabilityResponse_

typedef ::capabilities::StopCapabilityResponse_<std::allocator<void> > StopCapabilityResponse;

typedef boost::shared_ptr< ::capabilities::StopCapabilityResponse > StopCapabilityResponsePtr;
typedef boost::shared_ptr< ::capabilities::StopCapabilityResponse const> StopCapabilityResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::capabilities::StopCapabilityResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::capabilities::StopCapabilityResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace capabilities

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'capabilities': ['/tmp/binarydeb/ros-indigo-capabilities-0.2.0/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::capabilities::StopCapabilityResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::capabilities::StopCapabilityResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::capabilities::StopCapabilityResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::capabilities::StopCapabilityResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::capabilities::StopCapabilityResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::capabilities::StopCapabilityResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::capabilities::StopCapabilityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6ccdb752b565be6d250259ff3d0c7ea1";
  }

  static const char* value(const ::capabilities::StopCapabilityResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6ccdb752b565be6dULL;
  static const uint64_t static_value2 = 0x250259ff3d0c7ea1ULL;
};

template<class ContainerAllocator>
struct DataType< ::capabilities::StopCapabilityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "capabilities/StopCapabilityResponse";
  }

  static const char* value(const ::capabilities::StopCapabilityResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::capabilities::StopCapabilityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool successful\n\
";
  }

  static const char* value(const ::capabilities::StopCapabilityResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::capabilities::StopCapabilityResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.successful);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StopCapabilityResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::capabilities::StopCapabilityResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::capabilities::StopCapabilityResponse_<ContainerAllocator>& v)
  {
    s << indent << "successful: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.successful);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAPABILITIES_MESSAGE_STOPCAPABILITYRESPONSE_H
