(cl:defpackage capabilities-msg
  (:use )
  (:export
   "<CAPABILITYEVENT>"
   "CAPABILITYEVENT"
   "<REMAPPING>"
   "REMAPPING"
   "<CAPABILITY>"
   "CAPABILITY"
   "<CAPABILITYSPEC>"
   "CAPABILITYSPEC"
   "<RUNNINGCAPABILITY>"
   "RUNNINGCAPABILITY"
  ))

